int story();
int tutorial(int x, int y, int f);
void printcharacter(int x, int y, int s);
void printend(int x, int y);
int printhome();
void printpath(int x, int y);
void lightenpath(int x, int y);
void printdarkness(int x, int y);
void printdir(int x, int y, int u);
void printlight(int x, int y);
void printwall(int x, int y);
//void printmirror_upleft(int x, int y);
//void printmirror_downleft(int x, int y);
void printglass(int x, int y);
void printblock(int x, int y);
void printinactiveport(int x, int y);
void printai(int x, int y);
void printai2(int x, int y);
void printdeadai(int x, int y);
